// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/lrayt/small-sparrow/example/app/handler"
	main2 "github.com/lrayt/small-sparrow/example/cmd"
)

// Injectors from wire.go:

func InitExampleServer() (*main2.ExampleServer, func(), error) {
	httpHandler := handler.NewHttpHandler()
	exampleServer := main2.NewExampleServer(httpHandler)
	return exampleServer, func() {
	}, nil
}

// wire.go:

// HandlerProvider 获取参数
var HandlerProvider = wire.NewSet(handler.NewHttpHandler)
